// ════════════════════════════════════════════════════════════════════
// PflegeDeutsch — Seed Data (dùng cho việc nhập dữ liệu mặc định lần đầu)
// File này được admin.html dùng khi nhấn nút "Nhập dữ liệu mặc định".
// Có thể sửa file này để thay đổi nội dung seed.
// ════════════════════════════════════════════════════════════════════

window.SEED_CAT_META = {
  patient:        {l:'Bệnh nhân',     ic:'👤'},
  colleague:      {l:'Đồng nghiệp',   ic:'👥'},
  handover:       {l:'Bàn giao ca',   ic:'🔄'},
  emergency:      {l:'Khẩn cấp',      ic:'🚨'},
  vocab:          {l:'Chuyên ngành',  ic:'📚'},
  anatomy:        {l:'Giải phẫu',     ic:'🫀'},
  medication:     {l:'Thuốc & ĐT',    ic:'💊'},
  documentation: {l:'Hồ sơ',         ic:'📋'},
  nursing_process:{l:'Quy trình ĐD', ic:'🩺'},
  mental:         {l:'Tâm thần & Lão',ic:'🧠'},
};

window.SEED_DATA = (function(){
const DATA={
patient:[
  {g:"Chào hỏi",i:[
    {de:"Guten Morgen! Wie geht es Ihnen heute?",vi:"Chào buổi sáng! Hôm nay bạn thế nào?"},
    {de:"Mein Name ist ___, ich bin Ihre Pflegefachkraft.",vi:"Tôi là ___, điều dưỡng phụ trách bạn."},
    {de:"Ich übernehme jetzt Ihre Pflege.",vi:"Từ bây giờ tôi sẽ chăm sóc cho bạn."},
    {de:"Ich bin heute für Sie zuständig.",vi:"Hôm nay tôi là người phụ trách bạn."},
    {de:"Darf ich mich kurz vorstellen?",vi:"Cho phép tôi tự giới thiệu một chút?"},
  ]},
  {g:"Hỏi triệu chứng",i:[
    {de:"Haben Sie Schmerzen? Wo genau?",vi:"Bạn có đau không? Đau ở đâu?"},
    {de:"Wie stark auf einer Skala von 1 bis 10?",vi:"Mức độ đau từ 1 đến 10?"},
    {de:"Ist der Schmerz stechend / dumpf / brennend?",vi:"Đau nhói / âm ỉ / rát bỏng?"},
    {de:"Strahlt der Schmerz irgendwo hin aus?",vi:"Cơn đau có lan ra đâu không?"},
    {de:"Seit wann haben Sie diese Beschwerden?",vi:"Triệu chứng này từ bao giờ?"},
    {de:"Haben Sie Atemnot / Übelkeit / Schwindel?",vi:"Bạn có khó thở / buồn nôn / chóng mặt không?"},
    {de:"Haben Sie Fieber oder Schüttelfrost?",vi:"Bạn có sốt hoặc rét run không?"},
    {de:"Haben Sie Husten oder Auswurf?",vi:"Bạn có ho hoặc khạc đờm không?"},
    {de:"Schlafen Sie gut?",vi:"Bạn ngủ có ngon không?"},
    {de:"Haben Sie heute schon gegessen und getrunken?",vi:"Hôm nay bạn đã ăn và uống chưa?"},
  ]},
  {g:"Thủ thuật & Chăm sóc",i:[
    {de:"Ich messe jetzt Ihren Blutdruck.",vi:"Tôi sẽ đo huyết áp cho bạn."},
    {de:"Ich nehme Ihre Körpertemperatur.",vi:"Tôi sẽ đo nhiệt độ cơ thể."},
    {de:"Ich messe Ihren Blutzucker.",vi:"Tôi sẽ đo đường huyết."},
    {de:"Ich gebe Ihnen jetzt Ihre Medikamente.",vi:"Bây giờ tôi cho bạn uống thuốc."},
    {de:"Ich muss Ihnen eine Spritze geben.",vi:"Tôi cần tiêm cho bạn.",n:"Thêm: 'Das tut kurz weh' = đau một chút"},
    {de:"Ich lege Ihnen einen Venenzugang.",vi:"Tôi sẽ đặt đường truyền tĩnh mạch."},
    {de:"Ich wechsle jetzt Ihren Verband.",vi:"Tôi sẽ thay băng cho bạn."},
    {de:"Bitte bleiben Sie ruhig liegen.",vi:"Xin hãy nằm yên."},
    {de:"Können Sie sich auf die Seite drehen?",vi:"Bạn có thể nằm nghiêng không?"},
    {de:"Ich helfe Ihnen beim Aufstehen.",vi:"Tôi sẽ giúp bạn ngồi dậy."},
    {de:"Bitte atmen Sie tief ein und aus.",vi:"Xin hít vào và thở ra thật sâu."},
  ]},
  {g:"Vệ sinh & Dinh dưỡng",i:[
    {de:"Möchten Sie sich waschen? Ich helfe Ihnen.",vi:"Bạn muốn tắm rửa không? Tôi giúp bạn."},
    {de:"Brauchen Sie die Bettpfanne / Urinflasche?",vi:"Bạn cần bô / bình tiểu không?"},
    {de:"Klingeln Sie bitte, wenn Sie etwas brauchen.",vi:"Nếu cần gì hãy bấm chuông nhé."},
    {de:"Haben Sie Allergien gegen Lebensmittel?",vi:"Bạn có dị ứng thức ăn nào không?"},
    {de:"Bitte trinken Sie ausreichend – 1,5 Liter täglich.",vi:"Hãy uống đủ nước – 1,5 lít mỗi ngày."},
    {de:"Erholen Sie sich gut!",vi:"Chúc bạn mau bình phục!"},
  ]},
],
colleague:[
  {g:"Giao tiếp chung",i:[
    {de:"Können Sie mir kurz helfen?",vi:"Bạn giúp tôi một chút được không?"},
    {de:"Ich brauche Unterstützung bei Zimmer ___.",vi:"Tôi cần hỗ trợ ở phòng ___."},
    {de:"Das liegt außerhalb meiner Kompetenz.",vi:"Điều đó nằm ngoài thẩm quyền của tôi.",n:"Quan trọng khi gặp tình huống vượt khả năng"},
    {de:"Ich informiere den Arzt sofort.",vi:"Tôi sẽ báo bác sĩ ngay."},
    {de:"Haben Sie das schon dokumentiert?",vi:"Bạn đã ghi vào hồ sơ chưa?"},
  ]},
  {g:"Báo cáo SBAR",i:[
    {de:"Ich möchte Ihnen einen Patienten vorstellen.",vi:"Tôi muốn báo cáo về một bệnh nhân."},
    {de:"Patient ___, ___ Jahre, Zimmer ___.",vi:"Bệnh nhân ___, ___ tuổi, phòng ___."},
    {de:"Aufnahme wegen ___. Aktuell klagt er über ___.",vi:"Nhập viện vì ___. Hiện than thở về ___."},
    {de:"Vitalzeichen: RR ___, Puls ___, Temp ___, SpO2 ___.",vi:"Sinh hiệu: HA ___, mạch ___, nhiệt độ ___, SpO2 ___."},
    {de:"Ich bitte um eine Anordnung für ___.",vi:"Tôi xin chỉ định cho ___."},
    {de:"Bitte schauen Sie sich den Patienten an.",vi:"Nhờ bác sĩ xem qua bệnh nhân."},
    {de:"Habe ich das richtig verstanden?",vi:"Tôi hiểu đúng chưa?"},
    {de:"Können Sie das bitte wiederholen?",vi:"Bạn có thể nhắc lại không?"},
  ]},
],
handover:[
  {g:"Cấu trúc SBAR",i:[
    {de:"S: Patient ___, ___ Jahre, Zimmer ___, aufgenommen wegen ___.",vi:"S: BN ___, ___ tuổi, phòng ___, nhập vì ___."},
    {de:"B: Vorerkrankungen: ___. Dauermedikation: ___.",vi:"B: Bệnh nền: ___. Thuốc dùng thường xuyên: ___."},
    {de:"A: Aktuell ist der Patient stabil / instabil.",vi:"A: BN hiện đang ổn định / không ổn định."},
    {de:"R: Bitte achten Sie besonders auf ___.",vi:"R: Nhờ chú ý đặc biệt đến ___."},
  ]},
  {g:"Nội dung bàn giao",i:[
    {de:"Die Medikamente wurden vollständig gegeben.",vi:"Thuốc đã được cho đầy đủ."},
    {de:"Die Abendmedikation steht noch aus.",vi:"Thuốc buổi tối vẫn chưa cho."},
    {de:"Die Infusion läuft mit ___ ml/h, Rest ___ ml.",vi:"Dịch truyền ___ ml/h, còn lại ___ ml."},
    {de:"Der Verband wurde heute Morgen gewechselt.",vi:"Đã thay băng sáng nay."},
    {de:"Patient war ruhig / unruhig / verwirrt.",vi:"BN bình thường / kích động / lú lẫn."},
    {de:"Stuhlgang: vorhanden / nicht vorhanden.",vi:"Đại tiện: có / không có."},
    {de:"Arzt und Angehörige wurden informiert.",vi:"Đã báo bác sĩ và gia đình."},
    {de:"Sonst keine Auffälligkeiten.",vi:"Ngoài ra không có gì bất thường."},
  ]},
],
emergency:[
  {g:"Gọi hỗ trợ",i:[
    {de:"Notruf! Kommen Sie sofort zu Zimmer ___!",vi:"Cấp cứu! Đến phòng ___ ngay!",n:"Nói to, rõ, chậm"},
    {de:"Ich brauche sofort Hilfe!",vi:"Tôi cần giúp đỡ ngay!"},
    {de:"Bitte rufen Sie das Reanimationsteam!",vi:"Gọi đội hồi sức ngay!"},
    {de:"Wir brauchen den Defibrillator sofort!",vi:"Cần máy sốc điện ngay!"},
  ]},
  {g:"Mô tả & Hành động",i:[
    {de:"Patient ist bewusstlos, reagiert nicht.",vi:"BN bất tỉnh, không phản ứng."},
    {de:"Keine Atmung und kein Puls feststellbar.",vi:"Không có nhịp thở và mạch."},
    {de:"Verdacht auf Herzinfarkt – Brustschmerzen.",vi:"Nghi nhồi máu cơ tim – đau ngực."},
    {de:"Verdacht auf Schlaganfall – Gesichtslähmung.",vi:"Nghi đột quỵ – liệt mặt.",n:"Test FAST: Face-Arm-Speech-Time"},
    {de:"Ich beginne mit der Herzdruckmassage!",vi:"Tôi bắt đầu ép tim!"},
    {de:"Defi laden – Alle weg vom Patienten!",vi:"Sạc máy sốc – Tất cả đứng ra xa!"},
    {de:"Geben Sie O2 über Maske mit 10–15 L/min!",vi:"Cho oxy qua mặt nạ 10–15 lít/phút!"},
    {de:"Dokumentieren Sie die Uhrzeit!",vi:"Ghi lại thời gian!"},
  ]},
],
vocab:[
  {g:"Bệnh lý tim mạch",i:[
    {de:"die Herzinsuffizienz",vi:"suy tim"},
    {de:"der Herzinfarkt (Myokardinfarkt)",vi:"nhồi máu cơ tim"},
    {de:"die Angina pectoris",vi:"đau thắt ngực"},
    {de:"das Vorhofflimmern",vi:"rung nhĩ"},
    {de:"die tiefe Venenthrombose (TVT)",vi:"huyết khối tĩnh mạch sâu"},
    {de:"die Lungenembolie",vi:"tắc mạch phổi"},
    {de:"die arterielle Hypertonie",vi:"tăng huyết áp"},
  ]},
  {g:"Bệnh lý hô hấp",i:[
    {de:"die Pneumonie",vi:"viêm phổi"},
    {de:"die COPD",vi:"bệnh phổi tắc nghẽn mãn tính"},
    {de:"das Asthma bronchiale",vi:"hen phế quản"},
    {de:"das Lungenödem",vi:"phù phổi"},
    {de:"die Schlafapnoe",vi:"ngưng thở khi ngủ"},
  ]},
  {g:"Bệnh lý khác",i:[
    {de:"der Schlaganfall (Apoplex)",vi:"đột quỵ"},
    {de:"die Epilepsie",vi:"động kinh"},
    {de:"der Diabetes mellitus Typ 1/2",vi:"đái tháo đường type 1/2"},
    {de:"die Niereninsuffizienz",vi:"suy thận"},
    {de:"die Leberzirrhose",vi:"xơ gan"},
    {de:"die Sepsis",vi:"nhiễm trùng huyết"},
    {de:"der Dekubitus",vi:"loét tỳ đè"},
    {de:"die Demenz",vi:"sa sút trí tuệ"},
  ]},
  {g:"Triệu chứng",i:[
    {de:"die Zyanose",vi:"tím tái"},
    {de:"das Ödem",vi:"phù nề"},
    {de:"die Tachykardie / Bradykardie",vi:"nhịp nhanh / nhịp chậm"},
    {de:"die Dyspnoe (Atemnot)",vi:"khó thở"},
    {de:"die Dysphagie",vi:"khó nuốt"},
    {de:"die Hemiparese",vi:"liệt nửa người"},
    {de:"die Aphasie",vi:"mất ngôn ngữ"},
    {de:"die Anurie / Oligurie",vi:"vô niệu / thiểu niệu"},
    {de:"die Hämatemesis",vi:"nôn ra máu"},
    {de:"die Hämaturie",vi:"tiểu ra máu"},
  ]},
  {g:"Dụng cụ y tế",i:[
    {de:"der periphere Venenkatheter (PVK)",vi:"catheter tĩnh mạch ngoại vi"},
    {de:"der zentralvenöse Katheter (ZVK)",vi:"catheter tĩnh mạch trung tâm"},
    {de:"der Blasenkatheter",vi:"ống thông tiểu"},
    {de:"die nasogastrale Sonde (NGT)",vi:"ống thông dạ dày mũi"},
    {de:"das Pulsoximeter",vi:"máy đo SpO2"},
    {de:"das Blutzuckermessgerät",vi:"máy đo đường huyết"},
    {de:"der Defibrillator / AED",vi:"máy sốc điện"},
    {de:"der Beatmungsbeutel (Ambu-Beutel)",vi:"bóng bóp hô hấp"},
    {de:"die Infusionspumpe / Spritzenpumpe",vi:"máy bơm truyền / bơm tiêm"},
    {de:"die Antidekubitusmatratze",vi:"đệm chống loét tỳ đè"},
  ]},
],
anatomy:[
  {g:"Đầu & Não",i:[
    {de:"das Gehirn",vi:"não"},{de:"der Hirnstamm",vi:"thân não"},{de:"das Kleinhirn",vi:"tiểu não"},
    {de:"die Schilddrüse",vi:"tuyến giáp"},{de:"die Hypophyse",vi:"tuyến yên"},
  ]},
  {g:"Tim & Phổi",i:[
    {de:"der linke / rechte Ventrikel",vi:"tâm thất trái / phải"},
    {de:"das linke / rechte Atrium",vi:"tâm nhĩ trái / phải"},
    {de:"die Mitralklappe / Aortenklappe",vi:"van hai lá / van động mạch chủ"},
    {de:"die Koronararterien",vi:"động mạch vành"},
    {de:"die Aorta",vi:"động mạch chủ"},
    {de:"die Bronchien / Alveolen",vi:"phế quản / phế nang"},
    {de:"das Zwerchfell",vi:"cơ hoành"},
  ]},
  {g:"Ổ bụng",i:[
    {de:"der Magen",vi:"dạ dày"},{de:"der Dünndarm / Dickdarm",vi:"ruột non / ruột già"},
    {de:"die Leber",vi:"gan"},{de:"die Gallenblase",vi:"túi mật"},
    {de:"die Bauchspeicheldrüse (Pankreas)",vi:"tuyến tụy"},
    {de:"die Milz",vi:"lá lách"},{de:"die Niere",vi:"thận"},
    {de:"die Harnblase",vi:"bàng quang"},{de:"die Nebenniere",vi:"tuyến thượng thận"},
  ]},
  {g:"Cơ xương & Mạch máu",i:[
    {de:"die Wirbelsäule",vi:"cột sống"},{de:"das Becken",vi:"khung chậu"},
    {de:"die Arterie / Vene / Kapillare",vi:"động mạch / tĩnh mạch / mao mạch"},
    {de:"das Erythrozyt / Leukozyten / Thrombozyt",vi:"hồng cầu / bạch cầu / tiểu cầu"},
    {de:"der Blutdruck (systolisch/diastolisch)",vi:"huyết áp tâm thu / tâm trương"},
  ]},
],
medication:[
  {g:"Đường dùng thuốc",i:[
    {de:"oral (p.o.) – per os",vi:"đường uống",n:"p.o. = per os"},
    {de:"intravenös (i.v.)",vi:"đường tĩnh mạch"},
    {de:"intramuskulär (i.m.)",vi:"đường tiêm bắp"},
    {de:"subkutan (s.c.)",vi:"đường tiêm dưới da"},
    {de:"transdermal / sublingual",vi:"qua da (miếng dán) / ngậm dưới lưỡi"},
    {de:"inhalativ / rektal",vi:"đường hít / đường hậu môn"},
  ]},
  {g:"Nhóm thuốc",i:[
    {de:"das Analgetikum / WHO-Stufe 1–3",vi:"thuốc giảm đau bậc 1–3"},
    {de:"das Antibiotikum / Antimykotikum",vi:"kháng sinh / kháng nấm"},
    {de:"das Antikoagulans",vi:"thuốc chống đông máu"},
    {de:"das Antihypertensivum / Diuretikum",vi:"hạ huyết áp / lợi tiểu"},
    {de:"das Insulin (Kurz-/Langzeit)",vi:"insulin tác dụng nhanh / chậm"},
    {de:"das Kortikosteroid",vi:"corticosteroid"},
    {de:"der Protonenpumpenhemmer (PPI)",vi:"ức chế bơm proton"},
    {de:"das Antiemetikum / Laxativum",vi:"chống nôn / nhuận tràng"},
  ]},
  {g:"Thuốc thông dụng",i:[
    {de:"Paracetamol / Metamizol",vi:"hạ sốt, giảm đau bậc 1"},
    {de:"Ibuprofen / Diclofenac",vi:"kháng viêm NSAID"},
    {de:"Morphin / Tramadol",vi:"giảm đau opioid mạnh / yếu"},
    {de:"Metoprolol / Bisoprolol",vi:"chẹn beta (tim mạch)"},
    {de:"Ramipril / Enalapril",vi:"ức chế ACE"},
    {de:"Furosemid / Spironolacton",vi:"lợi tiểu quai / kháng aldosteron"},
    {de:"Heparin / Enoxaparin (Clexane)",vi:"chống đông heparin / LMWH"},
    {de:"Pantoprazol / Omeprazol",vi:"PPI (giảm acid dạ dày)"},
    {de:"Ondansetron / Metoclopramid",vi:"chống nôn"},
    {de:"Lorazepam (Tavor) / Diazepam",vi:"an thần / chống động kinh"},
  ]},
  {g:"Dịch truyền & Giao tiếp thuốc",i:[
    {de:"NaCl 0,9% – Ringer-Laktat – Glukose 5%",vi:"muối sinh lý – Ringer – Glucose"},
    {de:"Nehmen Sie das Medikament ___ mal täglich.",vi:"Uống thuốc này ___ lần mỗi ngày."},
    {de:"Haben Sie Allergien gegen Medikamente?",vi:"Bạn có dị ứng thuốc nào không?"},
    {de:"Welche Medikamente nehmen Sie regelmäßig?",vi:"Bạn đang dùng thuốc gì thường xuyên?"},
  ]},
],
documentation:[
  {g:"Hồ sơ & Ghi chép",i:[
    {de:"die Patientenakte / Pflegedokumentation",vi:"hồ sơ bệnh án / hồ sơ điều dưỡng"},
    {de:"die Fieberkurve (Kurve)",vi:"phiếu theo dõi sinh hiệu"},
    {de:"die Arztanordnung / Pflegeplanung",vi:"y lệnh bác sĩ / kế hoạch chăm sóc"},
    {de:"der Entlassungsbrief / Aufnahmebogen",vi:"tóm tắt xuất viện / phiếu nhập viện"},
    {de:"das Sturzprotokoll",vi:"biên bản té ngã"},
  ]},
  {g:"Viết tắt quan trọng",i:[
    {de:"RR ___ / ___ mmHg",vi:"Huyết áp tâm thu / tâm trương",n:"RR = Riva-Rocci"},
    {de:"HF ___ /min · AF ___ /min · Temp ___ °C",vi:"Nhịp tim · Nhịp thở · Nhiệt độ"},
    {de:"SpO2 ___ % · BZ ___ mg/dl",vi:"Bão hòa oxy · Đường huyết"},
    {de:"GCS ___ / 15 · NRS ___ / 10",vi:"Điểm hôn mê Glasgow · Thang đau"},
    {de:"n.B. = nach Bedarf · V.a. = Verdacht auf",vi:"khi cần · nghi ngờ là"},
    {de:"o.B. = ohne Befund",vi:"không có phát hiện bất thường"},
    {de:"i.v. / i.m. / s.c. / p.o.",vi:"tĩnh mạch / bắp / dưới da / uống"},
  ]},
  {g:"Pháp lý & Đạo đức",i:[
    {de:"die informierte Einwilligung",vi:"đồng ý có thông tin (informed consent)"},
    {de:"die Schweigepflicht",vi:"nghĩa vụ bảo mật thông tin bệnh nhân"},
    {de:"die Patientenverfügung",vi:"di chúc điều trị"},
    {de:"die freiheitsentziehende Maßnahme (FEM)",vi:"biện pháp hạn chế tự do",n:"Cần y lệnh & quyết định tòa án"},
    {de:"die Meldepflicht (IfSG)",vi:"nghĩa vụ báo cáo bệnh truyền nhiễm"},
    {de:"MRSA / VRE / 3MRGN / 4MRGN",vi:"vi khuẩn đa kháng kháng sinh"},
    {de:"die hygienische Händedesinfektion",vi:"khử khuẩn tay (6 bước WHO)"},
  ]},
],
nursing_process:[
  {g:"5 bước quy trình",i:[
    {de:"1. Pflegeassessment – Informationssammlung",vi:"1. Thu thập thông tin / đánh giá"},
    {de:"2. Pflegediagnose (nach NANDA)",vi:"2. Chẩn đoán điều dưỡng"},
    {de:"3. Pflegeziele (SMART)",vi:"3. Đặt mục tiêu chăm sóc"},
    {de:"4. Pflegemaßnahmen planen & durchführen",vi:"4. Lập kế hoạch & thực hiện"},
    {de:"5. Evaluation / Wirkungskontrolle",vi:"5. Đánh giá & kiểm tra hiệu quả"},
  ]},
  {g:"Phòng ngừa (Prophylaxen)",i:[
    {de:"die Dekubitusprophylaxe",vi:"phòng ngừa loét tỳ đè"},
    {de:"die Sturzprophylaxe",vi:"phòng ngừa té ngã"},
    {de:"die Thromboseprophylaxe",vi:"phòng ngừa huyết khối"},
    {de:"die Pneumonieprophylaxe",vi:"phòng ngừa viêm phổi"},
    {de:"die Aspirationsprophylaxe",vi:"phòng ngừa hít sặc"},
    {de:"die Kontrakturprophylaxe",vi:"phòng ngừa co cứng khớp"},
    {de:"die Soorprophylaxe",vi:"phòng ngừa nấm miệng"},
    {de:"die Obstipationsprophylaxe",vi:"phòng ngừa táo bón"},
  ]},
  {g:"Thang điểm & Đánh giá",i:[
    {de:"die Braden-Skala",vi:"thang Braden – nguy cơ loét tỳ đè"},
    {de:"die Morse-Skala",vi:"thang Morse – nguy cơ té ngã"},
    {de:"der Barthel-Index",vi:"chỉ số Barthel – mức độ tự lập"},
    {de:"das MMSE",vi:"kiểm tra nhận thức tối thiểu"},
    {de:"das NRS 2002 / MUST-Score",vi:"sàng lọc nguy cơ dinh dưỡng"},
  ]},
  {g:"Kỹ thuật điều dưỡng",i:[
    {de:"die Wundversorgung / Verbandswechsel",vi:"chăm sóc vết thương / thay băng"},
    {de:"die subkutane / intramuskuläre Injektion",vi:"tiêm dưới da / tiêm bắp"},
    {de:"die Blutentnahme (venös / kapillär)",vi:"lấy máu tĩnh mạch / mao mạch"},
    {de:"das Absaugen (oropharyngeal/endotracheal)",vi:"hút đờm miệng hầu / nội khí quản"},
    {de:"das Stoma (Kolo-/Ileo-/Tracheostoma)",vi:"lỗ mở đại tràng / hồi tràng / khí quản"},
    {de:"die Lagerung: 30°-Lagerung",vi:"nằm nghiêng 30° – phòng loét tỳ đè"},
  ]},
],
mental:[
  {g:"Bệnh tâm thần",i:[
    {de:"die Schizophrenie",vi:"tâm thần phân liệt"},
    {de:"die bipolare Störung",vi:"rối loạn lưỡng cực"},
    {de:"die Major Depression",vi:"trầm cảm nặng"},
    {de:"die Angststörung / Panikstörung",vi:"rối loạn lo âu / hoảng loạn"},
    {de:"die Suizidalität",vi:"ý định tự tử"},
    {de:"das Delir (akute Verwirrtheit)",vi:"mê sảng / lú lẫn cấp"},
    {de:"die Substanzabhängigkeit",vi:"lệ thuộc chất"},
  ]},
  {g:"Giao tiếp tâm thần",i:[
    {de:"Fühlen Sie sich sicher?",vi:"Bạn có cảm thấy an toàn không?"},
    {de:"Haben Sie Gedanken, sich selbst zu verletzen?",vi:"Bạn có ý nghĩ tự làm hại không?",n:"Hỏi thẳng – không gây nguy hiểm"},
    {de:"Ich bin für Sie da. Sie sind hier sicher.",vi:"Tôi ở đây bên bạn. Bạn đang ở nơi an toàn."},
    {de:"Ich höre Ihnen zu.",vi:"Tôi đang lắng nghe bạn."},
  ]},
  {g:"Lão khoa",i:[
    {de:"die Multimorbidität",vi:"đa bệnh lý"},
    {de:"die Polypharmazie (≥5 Medikamente)",vi:"đa thuốc"},
    {de:"die Frailty (Gebrechlichkeit)",vi:"hội chứng suy yếu"},
    {de:"die Sarkopenie",vi:"mất cơ liên quan tuổi"},
    {de:"die Demenzpflege / Validation",vi:"chăm sóc sa sút trí tuệ / Validation"},
    {de:"die Sturzprävention im Alter",vi:"phòng té ngã ở người cao tuổi"},
  ]},
],
};

// ════════════════════════════════════════════════════════
// DIALOGUES
// ════════════════════════════════════════════════════════
const DIALOGUES=[
  {title:"Nhập viện – Hỏi thăm ban đầu",icon:"🏥",diff:"easy",lines:[
    {role:"nurse",de:"Guten Morgen! Mein Name ist Anna, ich bin Ihre Pflegefachkraft für heute.",vi:"Chào buổi sáng! Tôi là Anna, điều dưỡng phụ trách bạn hôm nay."},
    {role:"patient",de:"Guten Morgen. Ich bin Herr Nguyen.",vi:"Chào buổi sáng. Tôi là ông Nguyen."},
    {role:"nurse",de:"Wie geht es Ihnen heute, Herr Nguyen? Haben Sie gut geschlafen?",vi:"Hôm nay ông cảm thấy thế nào? Ông ngủ có ngon không?"},
    {role:"patient",de:"Nicht so gut. Ich habe Schmerzen im Bauch.",vi:"Không lắm. Tôi bị đau bụng."},
    {role:"nurse",de:"Das tut mir leid. Wie stark sind die Schmerzen auf einer Skala von 1 bis 10?",vi:"Tôi rất tiếc. Mức độ đau từ 1 đến 10 là bao nhiêu?"},
    {role:"patient",de:"Ungefähr eine 6.",vi:"Khoảng 6."},
    {role:"nurse",de:"Ich dokumentiere das und informiere den Arzt. Klingeln Sie bitte, wenn es schlimmer wird.",vi:"Tôi sẽ ghi lại và báo bác sĩ. Nhờ ông bấm chuông nếu đau hơn."},
  ]},
  {title:"Đo sinh hiệu & Thuốc",icon:"💊",diff:"easy",lines:[
    {role:"nurse",de:"Guten Morgen! Ich möchte Ihren Blutdruck und Puls messen.",vi:"Chào buổi sáng! Tôi muốn đo huyết áp và mạch của bạn."},
    {role:"patient",de:"Natürlich, kein Problem.",vi:"Được thôi, không sao."},
    {role:"nurse",de:"Ihr Blutdruck ist 135/85, Puls 78 – alles im normalen Bereich. Hier sind Ihre Morgentabletten.",vi:"Huyết áp 135/85, mạch 78 – đều trong phạm vi bình thường. Đây là thuốc buổi sáng của bạn."},
    {role:"patient",de:"Danke. Soll ich die Tabletten mit Wasser nehmen?",vi:"Cảm ơn. Tôi uống thuốc với nước nhé?"},
    {role:"nurse",de:"Ja, bitte nehmen Sie die Tabletten mit einem Glas Wasser nach dem Frühstück.",vi:"Vâng, uống thuốc với một cốc nước sau bữa sáng nhé."},
    {role:"patient",de:"Habe ich Allergien – darf ich das fragen?",vi:"Tôi có dị ứng không – tôi có thể hỏi không?"},
    {role:"nurse",de:"Laut Ihrer Akte keine bekannten Allergien. Wenn Sie Nebenwirkungen bemerken, sagen Sie mir bitte sofort Bescheid.",vi:"Theo hồ sơ, không có dị ứng nào được ghi nhận. Nếu bạn thấy tác dụng phụ, hãy báo tôi ngay."},
  ]},
  {title:"Bàn giao ca (Übergabe)",icon:"🔄",diff:"medium",lines:[
    {role:"nurse",de:"Ich gebe Ihnen jetzt die Übergabe für Zimmer 12.",vi:"Tôi bàn giao ca cho bạn về phòng 12."},
    {role:"nurse",de:"Patient Herr Schmidt, 68 Jahre, aufgenommen wegen dekompensierter Herzinsuffizienz.",vi:"BN ông Schmidt, 68 tuổi, nhập viện vì suy tim mất bù."},
    {role:"nurse",de:"Er ist aktuell stabil. Vitalzeichen: RR 130/80, Puls 88, Temp 37,1, SpO2 96% mit 2L O2.",vi:"Hiện đang ổn định. Sinh hiệu: HA 130/80, mạch 88, nhiệt độ 37,1, SpO2 96% với 2L oxy."},
    {role:"nurse",de:"Die Medikamente wurden vollständig gegeben. Die Furosemid-Infusion läuft mit 10 ml/h.",vi:"Thuốc đã cho đầy đủ. Truyền Furosemid đang chạy 10 ml/h."},
    {role:"nurse",de:"Bitte achten Sie auf die Urinausscheidung – Ziel: über 50 ml/h. Morgen steht eine Blutabnahme aus.",vi:"Chú ý lượng nước tiểu – mục tiêu trên 50 ml/h. Sáng mai cần lấy máu xét nghiệm."},
    {role:"nurse",de:"Haben Sie noch Fragen?",vi:"Bạn còn câu hỏi nào không?"},
    {role:"patient",de:"Nein, alles klar. Danke!",vi:"Không, rõ cả rồi. Cảm ơn!"},
  ]},
  {title:"Tình huống khẩn cấp – Ngã",icon:"🚨",diff:"hard",lines:[
    {role:"nurse",de:"Oh! Herr Müller, was ist passiert? Können Sie mich hören?",vi:"Ôi! Ông Müller, chuyện gì xảy ra vậy? Ông nghe tôi không?"},
    {role:"patient",de:"Ich bin... gefallen. Mein Bein tut weh.",vi:"Tôi... bị ngã. Chân tôi đau lắm."},
    {role:"nurse",de:"Ich bin bei Ihnen. Bitte bewegen Sie sich nicht. Ich hole sofort Hilfe.",vi:"Tôi ở đây với ông. Xin đừng cử động. Tôi đi gọi giúp đỡ ngay."},
    {role:"nurse",de:"[Ruft Kollegen] Notruf! Bitte kommen Sie sofort zu Zimmer 8! Patient gestürzt!",vi:"[Gọi đồng nghiệp] Cấp cứu! Đến phòng 8 ngay! Bệnh nhân bị ngã!"},
    {role:"nurse",de:"Herr Müller, ich überprüfe jetzt Ihre Vitalzeichen. Atmen Sie normal?",vi:"Ông Müller, tôi kiểm tra sinh hiệu. Ông thở bình thường không?"},
    {role:"patient",de:"Ja, ich atme... aber ich habe starke Schmerzen.",vi:"Có, tôi thở được... nhưng đau lắm."},
    {role:"nurse",de:"Ich gebe Ihnen etwas gegen den Schmerz. Verdacht auf Fraktur – ich dokumentiere alles und informiere den Arzt sofort.",vi:"Tôi sẽ cho ông thuốc giảm đau. Nghi gãy xương – tôi ghi lại tất cả và báo bác sĩ ngay."},
  ]},
  {title:"Chăm sóc vệ sinh cơ bản",icon:"🛁",diff:"easy",lines:[
    {role:"nurse",de:"Guten Morgen, Frau Weber. Möchten Sie sich heute waschen? Ich helfe Ihnen gerne.",vi:"Chào buổi sáng, bà Weber. Bà có muốn tắm rửa hôm nay không? Tôi rất vui được giúp."},
    {role:"patient",de:"Ja, das wäre schön. Aber ich kann mich kaum bewegen.",vi:"Vâng, tốt quá. Nhưng tôi gần như không thể cử động."},
    {role:"nurse",de:"Das ist kein Problem. Ich mache eine Ganzkörperwäsche im Bett. Ist Ihnen die Wassertemperatur so angenehm?",vi:"Không sao cả. Tôi sẽ tắm toàn thân cho bà trên giường. Nhiệt độ nước thế này có thoải mái không?"},
    {role:"patient",de:"Ja, das ist gut. Danke für Ihre Geduld.",vi:"Vâng, tốt lắm. Cảm ơn bạn đã kiên nhẫn."},
    {role:"nurse",de:"Gern geschehen. Ich achte auch auf den Hautzustand – ich sehe keine geröteten Stellen, das ist gut.",vi:"Không có gì. Tôi cũng kiểm tra tình trạng da – không thấy chỗ nào đỏ, tốt lắm."},
  ]},
  {title:"Báo cáo với bác sĩ",icon:"👨‍⚕️",diff:"medium",lines:[
    {role:"nurse",de:"Herr Doktor, darf ich kurz stören? Ich möchte Ihnen eine Patientin vorstellen.",vi:"Thưa bác sĩ, xin phép làm phiền một chút. Tôi muốn báo cáo về một bệnh nhân."},
    {role:"nurse",de:"Es handelt sich um Frau Kim, 55 Jahre, Zimmer 5. Sie klagt seit einer Stunde über zunehmende Atemnot.",vi:"Đây là bà Kim, 55 tuổi, phòng 5. Bà than khó thở ngày càng tăng từ một tiếng nay."},
    {role:"nurse",de:"Vitalzeichen: SpO2 88% unter 4L O2, RR 150/95, Puls 110, Atemfrequenz 26/min.",vi:"Sinh hiệu: SpO2 88% dưới 4L oxy, HA 150/95, mạch 110, nhịp thở 26 lần/phút."},
    {role:"nurse",de:"Ich vermute ein Lungenödem. Soll ich Furosemid 40mg i.v. geben?",vi:"Tôi nghi phù phổi. Tôi có nên cho Furosemid 40mg tĩnh mạch không?"},
    {role:"nurse",de:"Und ich habe den Patienten mit 30° hochgelagert und O2-Maske angelegt.",vi:"Tôi đã nâng đầu giường 30° và đặt mặt nạ oxy."},
  ]},
  {title:"Giải thích thủ thuật – Tiêm & Truyền",icon:"💉",diff:"medium",lines:[
    {role:"nurse",de:"Frau Tran, ich muss Ihnen jetzt eine Infusion legen. Darf ich Ihren Arm sehen?",vi:"Bà Tran, tôi cần đặt đường truyền cho bà bây giờ. Tôi xem tay bà được không?"},
    {role:"patient",de:"Natürlich. Aber ich habe Angst vor Nadeln.",vi:"Được. Nhưng tôi sợ kim tiêm."},
    {role:"nurse",de:"Das verstehe ich gut. Ich bin sehr vorsichtig. Sie werden nur kurz einen kleinen Druck spüren.",vi:"Tôi hiểu. Tôi sẽ rất cẩn thận. Bà sẽ chỉ cảm thấy một chút áp lực nhỏ."},
    {role:"nurse",de:"So, fertig! Der Zugang sitzt gut. Ich starte jetzt die Infusion mit NaCl 0,9%, 500ml über 4 Stunden.",vi:"Xong rồi! Đường truyền nằm tốt. Tôi bắt đầu truyền NaCl 0,9%, 500ml trong 4 tiếng."},
    {role:"patient",de:"Wann bekomme ich meine Medikamente?",vi:"Khi nào tôi được uống thuốc?"},
    {role:"nurse",de:"Ihre Tabletten bekommen Sie zum Frühstück um 8 Uhr. Falls Sie Schmerzen oder Rötungen an der Einstichstelle bemerken, sagen Sie mir bitte sofort Bescheid.",vi:"Thuốc viên của bà sẽ vào lúc 8 giờ sáng cùng bữa ăn. Nếu đau hoặc đỏ chỗ tiêm, hãy báo tôi ngay."},
  ]},
  {title:"Chăm sóc bệnh nhân mất trí nhớ",icon:"🧠",diff:"hard",lines:[
    {role:"nurse",de:"Guten Morgen, Herr Becker. Erkennen Sie mich? Ich bin Maria, Ihre Pflegefachkraft.",vi:"Chào buổi sáng, ông Becker. Ông có nhận ra tôi không? Tôi là Maria, điều dưỡng của ông."},
    {role:"patient",de:"Wo bin ich? Ich will nach Hause!",vi:"Tôi đang ở đâu vậy? Tôi muốn về nhà!"},
    {role:"nurse",de:"Sie sind im Krankenhaus, Herr Becker. Sie sind hier sicher. Ich passe auf Sie auf.",vi:"Ông đang ở bệnh viện, ông Becker. Ông an toàn ở đây. Tôi sẽ chăm sóc cho ông."},
    {role:"patient",de:"Meine Frau – wo ist meine Frau?",vi:"Vợ tôi – vợ tôi đâu rồi?"},
    {role:"nurse",de:"Ihre Frau kommt heute Nachmittag um 3 Uhr zu Besuch. Ich zeige Ihnen das Foto hier – sehen Sie?",vi:"Vợ ông sẽ đến thăm lúc 3 giờ chiều hôm nay. Tôi cho ông xem tấm ảnh này – ông thấy không?"},
    {role:"patient",de:"Ja... das ist Hilde. Meine Hilde.",vi:"Vâng... đó là Hilde. Hilde của tôi."},
    {role:"nurse",de:"Genau. Und bis dahin frühstücken wir erst. Ich helfe Ihnen beim Anziehen, ja?",vi:"Đúng vậy. Và đến lúc đó, trước tiên chúng ta ăn sáng đã. Tôi giúp ông mặc quần áo nhé?"},
  ]},
  {title:"Thuyết phục BN từ chối điều trị",icon:"🤝",diff:"hard",lines:[
    {role:"patient",de:"Ich will keine Spritze! Nehmen Sie das weg!",vi:"Tôi không muốn tiêm! Cất cái đó đi!"},
    {role:"nurse",de:"Ich höre Sie, Herr Park. Darf ich Ihnen kurz erklären, warum das wichtig ist?",vi:"Tôi nghe ông, ông Park. Ông cho phép tôi giải thích ngắn tại sao điều này quan trọng không?"},
    {role:"patient",de:"Ich habe Angst. Das tut doch so weh!",vi:"Tôi sợ. Nó đau lắm mà!"},
    {role:"nurse",de:"Das verstehe ich vollkommen. Darf ich fragen, was genau Sie befürchten?",vi:"Tôi hoàn toàn hiểu điều đó. Tôi có thể hỏi chính xác ông lo ngại điều gì không?"},
    {role:"nurse",de:"Diese Spritze ist Ihr Heparin – es schützt Sie vor Blutgerinnseln. Ohne es erhöht sich das Risiko für eine Thrombose.",vi:"Mũi tiêm này là Heparin – nó bảo vệ ông khỏi cục máu đông. Không có nó, nguy cơ huyết khối tăng cao."},
    {role:"patient",de:"Wenn Sie das so sagen... aber bitte seien Sie vorsichtig.",vi:"Nếu ông nói vậy... nhưng hãy cẩn thận nhé."},
    {role:"nurse",de:"Natürlich. Ich mache das sehr sanft. Sie können jederzeit stopp sagen.",vi:"Tất nhiên. Tôi sẽ làm rất nhẹ nhàng. Ông có thể nói dừng lại bất cứ lúc nào."},
  ]},
  {title:"Cuối ca – Nhận xét & Hồ sơ",icon:"📋",diff:"medium",lines:[
    {role:"nurse",de:"Ich komme gleich zu Ende meiner Schicht. Ich schreibe noch den Pflegebericht.",vi:"Tôi sắp hết ca. Tôi viết nốt báo cáo điều dưỡng."},
    {role:"nurse",de:"Herr Tran hat heute gut gegessen – 3/4 der Mahlzeit. Trinkmenge 1.200 ml. Stuhlgang einmal, normal.",vi:"Ông Tran hôm nay ăn tốt – 3/4 khẩu phần. Lượng nước uống 1.200 ml. Đại tiện một lần, bình thường."},
    {role:"nurse",de:"Blutdruck morgens 145/90 – Arzt informiert. Er hat eine neue Anordnung geschrieben: Blutdruck 3x täglich messen.",vi:"Huyết áp buổi sáng 145/90 – đã báo bác sĩ. Bác sĩ đã ra y lệnh mới: đo huyết áp 3 lần mỗi ngày."},
    {role:"nurse",de:"Besonderes Ereignis: Patient hat um 14:00 Uhr über Schwindel geklagt. Neurologische Symptome wurden ausgeschlossen.",vi:"Sự kiện đặc biệt: BN kêu chóng mặt lúc 14:00. Triệu chứng thần kinh đã được loại trừ."},
    {role:"nurse",de:"Alles dokumentiert. Übergabe an Spätschicht erfolgt. Gute Nacht, Kollegen!",vi:"Tất cả đã được ghi chép. Đã bàn giao cho ca chiều. Chúc đồng nghiệp ngủ ngon!"},
  ]},
];
  return {DATA, DIALOGUES};
})();

window.SEED_DATA_OBJ = window.SEED_DATA.DATA;
window.SEED_DIALOGUES = window.SEED_DATA.DIALOGUES;
